---
name: Joseferson
surname: Barreto
position: "Cientista de Dados"
#position: "Estatístico"
address: "Campina Grande"
profilepic: "./img/me.png"
www: "josefersonbarreto.github.io/portifolio"
email: "joseferson7@gmail.com"
github: JosefersonBarreto
linkedin: joseferson-barreto
orcid: 58429-515
Phone: "+5581981307467"
social mídia: "+55819813977467"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
# headcolor: 00008b
# color: 00008b
aboutme: "Tenho mais de três anos de experiência em análise de dados e programação em linguagens como R, Python
e T‑SQL. Atuei como analista de dados por um ano e meio no PROCON Municipal de Campina Grande, PB.
Tenho uma paixão profunda por programação, automação e inteligência artificial. Inclusive, este currículo
foi feito com código."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )


# tinytex::parse_install("CV.log")



xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

# Trabalhos

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Educação

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )

```

# Soft Skills 

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```




# Hard  Skills 

```{r SKILLS2}

skills2 %>%
  detailed_entries(
    with = area,
    what = skills
  )

```
<!-- # Honors -->

<!-- ```{r HONORS} -->

<!-- honors %>% -->
<!--   detailed_entries( -->
<!--     with = area, -->
<!--     what = accomplishment, -->
<!--     why = detail, -->
<!--     when = year, -->
<!--     where = where -->
<!--   ) -->

<!-- ``` -->

# Projetos

```{r PROJECTS}

projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```



\pagebreak



# Palestras Apresentadas 

```{r palest}

palest %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

<!-- # Works -->

<!-- ```{r WORKS} -->

<!-- works %>% -->
<!--   detailed_entries( -->
<!--     with = area, -->
<!--     what = accomplishment, -->
<!--     why = detail, -->
<!--     when = year, -->
<!--     where = where -->
<!--   ) -->

<!-- ``` -->


# Certifications

```{r CERTIFICATIONS}

certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```


# Idiomas 



```{r idiom}

idiom %>%
  detailed_entries(
    with = area,
    what = skills
  )

```